import { useEffect, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { ArrowLeft, Pencil, Mail, Phone, MapPin, CalendarDays, GraduationCap, Trash2 } from 'lucide-react'
import { deleteStudent, getStudent } from '../api'
import StatusBadge from '../components/StatusBadge'

export default function StudentDetails() {
  const { id } = useParams(), navigate = useNavigate(), [student,setStudent]=useState(null)
  useEffect(()=>{getStudent(id).then(r=>setStudent(r.data))},[id])
  if(!student) return <div className="py-20 text-center text-sm text-slate-500">Loading student profile…</div>
  const remove=async()=>{if(window.confirm('Delete this student record?')){await deleteStudent(id);navigate('/students')}}
  return <div className="mx-auto max-w-5xl space-y-5"><Link to="/students" className="inline-flex items-center gap-2 text-sm font-semibold text-slate-500 hover:text-slate-900"><ArrowLeft size={16}/> All students</Link><div className="card overflow-hidden"><div className="bg-gradient-to-br from-slate-950 to-indigo-950 px-6 py-8 text-white sm:px-8"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div className="flex items-center gap-4"><div className="grid h-20 w-20 shrink-0 place-items-center rounded-3xl bg-white/10 text-xl font-extrabold ring-1 ring-white/15">{student.first_name[0]}{student.last_name[0]}</div><div><p className="text-sm text-indigo-200">{student.student_id}</p><h2 className="mt-1 text-3xl font-extrabold tracking-tight">{student.full_name}</h2><p className="mt-1 text-sm text-slate-300">{student.department_code} · Semester {student.semester}</p></div></div><StatusBadge status={student.status}/></div></div><div className="grid gap-6 p-6 sm:grid-cols-2 sm:p-8"><Info icon={Mail} label="Email" value={student.email}/><Info icon={Phone} label="Phone" value={student.phone || 'Not provided'}/><Info icon={MapPin} label="Address" value={student.address || 'Not provided'}/><Info icon={CalendarDays} label="Date of birth" value={student.date_of_birth || 'Not provided'}/><Info icon={GraduationCap} label="Department" value={`${student.department_code} — ${student.department_name}`}/><Info icon={GraduationCap} label="Enrollment" value={`${student.enrollment_year} · Semester ${student.semester}`}/></div><div className="border-t border-slate-100 bg-slate-50/70 p-5 sm:px-8"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><p className="text-xs font-semibold uppercase tracking-wide text-slate-400">Academic performance</p><p className="mt-1 text-2xl font-extrabold">{Number(student.gpa).toFixed(2)} <span className="text-sm font-medium text-slate-400">/ 4.00 GPA</span></p></div><div className="flex gap-2"><Link to={`/students/${id}/edit`} className="btn-primary"><Pencil size={16}/> Edit profile</Link><button onClick={remove} className="btn-secondary text-rose-600 hover:bg-rose-50"><Trash2 size={16}/> Delete</button></div></div></div></div></div>
}
function Info({icon:Icon,label,value}){return <div className="flex gap-3"><div className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-slate-100 text-slate-500"><Icon size={17}/></div><div><p className="text-xs font-semibold uppercase tracking-wide text-slate-400">{label}</p><p className="mt-1 text-sm font-semibold text-slate-800">{value}</p></div></div>}
