import { useEffect, useState } from 'react'
import { Link, useSearchParams } from 'react-router-dom'
import { Plus, Search, SlidersHorizontal, Eye, Pencil, Trash2, ChevronLeft, ChevronRight, X } from 'lucide-react'
import { deleteStudent, getDepartments, getStudents } from '../api'
import StatusBadge from '../components/StatusBadge'

export default function Students() {
  const [params, setParams] = useSearchParams()
  const [students, setStudents] = useState([]), [departments, setDepartments] = useState([]), [count, setCount] = useState(0), [loading, setLoading] = useState(true)
  const search = params.get('search') || '', status = params.get('status') || '', department = params.get('department') || ''
  const load = () => { setLoading(true); getStudents({search, status, department}).then(r => { setStudents(r.data); setCount(r.data.length) }).finally(() => setLoading(false)) }
  useEffect(() => { getDepartments().then(r => setDepartments(r.data)) }, [])
  useEffect(() => { load() }, [search, status, department])
  const setFilter = (key, value) => { const p = new URLSearchParams(params); value ? p.set(key, value) : p.delete(key); setParams(p) }
  const remove = async (id) => { if (!window.confirm('Delete this student record?')) return; await deleteStudent(id); load() }
  return <div className="space-y-5">
    <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><p className="text-sm text-slate-500">{count} records found</p></div><Link to="/students/new" className="btn-primary"><Plus size={18}/> Add student</Link></div>
    <div className="card overflow-hidden"><div className="flex flex-col gap-3 border-b border-slate-100 p-4 lg:flex-row"><div className="relative flex-1"><Search className="absolute left-3.5 top-3 text-slate-400" size={17}/><input value={search} onChange={e => setFilter('search', e.target.value)} placeholder="Search by name, ID or email…" className="input pl-10"/></div><select value={department} onChange={e => setFilter('department', e.target.value)} className="input lg:w-52"><option value="">All departments</option>{departments.map(d => <option value={d.id} key={d.id}>{d.code} — {d.name}</option>)}</select><select value={status} onChange={e => setFilter('status', e.target.value)} className="input lg:w-40"><option value="">All status</option><option value="active">Active</option><option value="inactive">Inactive</option><option value="graduated">Graduated</option></select>{(search || status || department) && <button className="btn-secondary" onClick={() => setParams({})}><X size={16}/> Clear</button>}</div>
      <div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3.5 font-semibold">Student</th><th className="px-5 py-3.5 font-semibold">Department</th><th className="px-5 py-3.5 font-semibold">Semester</th><th className="px-5 py-3.5 font-semibold">GPA</th><th className="px-5 py-3.5 font-semibold">Status</th><th className="px-5 py-3.5 text-right font-semibold">Actions</th></tr></thead><tbody className="divide-y divide-slate-100">{loading ? <tr><td colSpan="6" className="px-5 py-16 text-center text-slate-500">Loading students…</td></tr> : students.length ? students.map(s => <tr key={s.id} className="hover:bg-slate-50/70"><td className="px-5 py-4"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-full bg-indigo-50 text-xs font-bold text-indigo-600">{s.first_name[0]}{s.last_name[0]}</div><div><Link className="font-semibold hover:text-indigo-600" to={`/students/${s.id}`}>{s.full_name}</Link><p className="mt-0.5 text-xs text-slate-500">{s.student_id} · {s.email}</p></div></div></td><td className="px-5 py-4"><span className="font-medium">{s.department_code}</span><p className="text-xs text-slate-500">{s.department_name}</p></td><td className="px-5 py-4 text-slate-600">Semester {s.semester}</td><td className="px-5 py-4 font-bold">{Number(s.gpa).toFixed(2)}</td><td className="px-5 py-4"><StatusBadge status={s.status}/></td><td className="px-5 py-4"><div className="flex justify-end gap-1"><Link to={`/students/${s.id}`} title="View" className="rounded-lg p-2 text-slate-500 hover:bg-slate-100 hover:text-indigo-600"><Eye size={17}/></Link><Link to={`/students/${s.id}/edit`} title="Edit" className="rounded-lg p-2 text-slate-500 hover:bg-slate-100 hover:text-indigo-600"><Pencil size={17}/></Link><button onClick={() => remove(s.id)} title="Delete" className="rounded-lg p-2 text-slate-500 hover:bg-rose-50 hover:text-rose-600"><Trash2 size={17}/></button></div></td></tr>) : <tr><td colSpan="6" className="px-5 py-16 text-center"><div className="mx-auto max-w-sm"><SlidersHorizontal className="mx-auto text-slate-300" size={28}/><p className="mt-3 font-semibold">No students found</p><p className="mt-1 text-sm text-slate-500">Try changing your search or filters.</p></div></td></tr>}</tbody></table></div>
      <div className="flex items-center justify-between border-t border-slate-100 px-5 py-3.5 text-xs text-slate-500"><span>Showing {students.length} of {count}</span><div className="flex gap-1"><button className="rounded-lg border border-slate-200 p-2 text-slate-400"><ChevronLeft size={15}/></button><button className="rounded-lg border border-slate-200 p-2 text-slate-400"><ChevronRight size={15}/></button></div></div>
    </div>
  </div>
}
