import { useEffect, useState } from 'react'
import { ArrowLeft, Save, UserRound } from 'lucide-react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { createStudent, getDepartments, getStudent, updateStudent } from '../api'

const empty = { student_id:'', first_name:'', last_name:'', email:'', phone:'', date_of_birth:'', gender:'', address:'', department:'', semester:1, enrollment_year:2026, status:'active', gpa:0 }
export default function StudentForm() {
  const { id } = useParams(), navigate = useNavigate(), editing = Boolean(id)
  const [form, setForm] = useState(empty), [departments, setDepartments] = useState([]), [error, setError] = useState(''), [saving, setSaving] = useState(false)
  useEffect(() => { getDepartments().then(r => setDepartments(r.data)); if (editing) getStudent(id).then(r => setForm(r.data)) }, [id])
  const change = e => setForm(f => ({...f, [e.target.name]: e.target.value}))
  const submit = async e => { e.preventDefault(); setSaving(true); setError(''); try { const payload = {...form, department: Number(form.department), semester:Number(form.semester), enrollment_year:Number(form.enrollment_year), gpa:Number(form.gpa)}; editing ? await updateStudent(id,payload) : await createStudent(payload); navigate(editing ? `/students/${id}` : '/students') } catch (err) { setError(Object.values(err.response?.data || {}).flat().join(' ') || 'Could not save the student.') } finally { setSaving(false) } }
  return <div className="mx-auto max-w-4xl space-y-5"><Link to={editing ? `/students/${id}` : '/students'} className="inline-flex items-center gap-2 text-sm font-semibold text-slate-500 hover:text-slate-900"><ArrowLeft size={16}/> Back to students</Link><div><h2 className="text-2xl font-extrabold tracking-tight">{editing ? 'Edit student' : 'Add new student'}</h2><p className="mt-1 text-sm text-slate-500">Keep the student's personal and academic information up to date.</p></div>
    <form onSubmit={submit} className="card p-5 sm:p-7"><Section title="Personal information" icon={UserRound}/><div className="grid gap-5 md:grid-cols-2"><Field label="Student ID" name="student_id" value={form.student_id} onChange={change} required placeholder="e.g. STU-2026-007"/><Field label="Email address" name="email" type="email" value={form.email} onChange={change} required placeholder="student@example.com"/><Field label="First name" name="first_name" value={form.first_name} onChange={change} required/><Field label="Last name" name="last_name" value={form.last_name} onChange={change} required/><Field label="Phone" name="phone" value={form.phone} onChange={change} placeholder="+977 98XXXXXXXX"/><Field label="Date of birth" name="date_of_birth" type="date" value={form.date_of_birth || ''} onChange={change}/><Select label="Gender" name="gender" value={form.gender} onChange={change} options={[['','Select gender'],['male','Male'],['female','Female'],['other','Other']]}/><Field label="Address" name="address" value={form.address} onChange={change} placeholder="City, District"/></div>
      <div className="my-8 border-t border-slate-100"/><Section title="Academic information"/><div className="grid gap-5 md:grid-cols-2"><Select label="Department" name="department" value={form.department} onChange={change} required options={[['','Select department'],...departments.map(d => [d.id,`${d.code} — ${d.name}`])]}/><Select label="Status" name="status" value={form.status} onChange={change} options={[['active','Active'],['inactive','Inactive'],['graduated','Graduated']]}/><Field label="Semester" name="semester" type="number" min="1" max="12" value={form.semester} onChange={change}/><Field label="Enrollment year" name="enrollment_year" type="number" value={form.enrollment_year} onChange={change}/><Field label="GPA" name="gpa" type="number" min="0" max="4" step="0.01" value={form.gpa} onChange={change}/></div>
      {error && <div className="mt-6 rounded-xl border border-rose-100 bg-rose-50 px-4 py-3 text-sm text-rose-700">{error}</div>}<div className="mt-8 flex justify-end gap-3 border-t border-slate-100 pt-5"><Link to={editing ? `/students/${id}` : '/students'} className="btn-secondary">Cancel</Link><button disabled={saving} className="btn-primary"><Save size={17}/>{saving ? 'Saving…' : editing ? 'Save changes' : 'Create student'}</button></div>
    </form>
  </div>
}
function Section({title,icon:Icon}) { return <div className="mb-5 flex items-center gap-3">{Icon && <div className="grid h-9 w-9 place-items-center rounded-xl bg-indigo-50 text-indigo-600"><Icon size={18}/></div>}<div><h3 className="font-bold">{title}</h3><p className="text-xs text-slate-500">Enter accurate information for this record.</p></div></div> }
function Field({label,name,...props}) { return <label><span className="label">{label}</span><input className="input" name={name} {...props}/></label> }
function Select({label,name,options,...props}) { return <label><span className="label">{label}</span><select className="input" name={name} {...props}>{options.map(([v,t]) => <option key={v} value={v}>{t}</option>)}</select></label> }
